### ISSUE TITLE
How to Obtain Authenticator's Attenstation Certificate

### ISSUE THREAD

**Issue by gurudeep-singh** [LedgerHQ/ledger-u2f-javacard#3]
I am trying to install U2F applet on a different JavaCard 3.x and can you please explain where to get these attestation certificate and attestation private key? I believe this has already been done by LedgerWallet.
Once this certificate is obtained, in what format certificate data is loaded in JavaCard 3.x smart card?

**Comment by btchip** [comment]
Hi

Yes, this is done by the provisioning system. If you want to install it
yourself, you can refer to the "install" instructions
https://github.com/ledgerhq/ledger-u2f-javacard#installing - the
certificate is expected to be DER encoded.

On 2 February 2016 at 07:55, gurudeep-singh notifications@github.com
wrote:

> I am trying to install U2F applet on a different JavaCard 3x and can you
> please explain where to get these attestation certificate and attestation
> private key? I believe this has already been done by LedgerWallet
> Once this certificate is obtained in what format certificate data is
> loaded in JavaCard 3x smart card?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LedgerHQ/ledger-u2f-javacard/issues/3.

## 

Nicolas Bacca
CEO http://www.simulity.com/
Mobile +33 6 30 79 86 54 - Skype nicolas_bacca.pro

**Comment by gurudeep-singh** [comment]
Thanks for quick reply. 
How can I get an attestation certificate from FIDO Alliance such as one obtained by LedgerWallet? Is there any established process by FIDO Alliance which is followed by authenticator vendors to obtain an attestation certificate?
If yes then would it possible for you to share that information?

**Comment by btchip** [comment]
You need to be a FIDO member or pass a vendor certification to get an
attestation certificate that'll be officially recognized as a FIDO vendor
metadata - but the good news is that this is absolutely not necessary to
test or deploy your product. You can use any self signed certificate and it
will work as servers are not checking it and adding that check is not
planned in order to support the growth of the protocol - just don't claim
you're a FIDO vendor yourself.
